version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-users-db
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '49160:8080'
    expose:
      # Opens port 8080 on the container
      - '8080'
      # Where our data will be persisted
    volumes:
      - users-db:/var/lib/mysql
# Names our volume
volumes:
  users-db: