name: publish

on:
  push:
    branches:
      - development

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/auth-microservice-development -f auth-microservice/Dockerfile .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/auth-microservice-development
      #- name: Build
      #  run: |
      #    gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/auth-microservice

      - name: Deploy
        run: |
          gcloud run deploy auth-microservice-development \
          --region ${{ secrets.GCP_REGION }} \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/auth-microservice-development \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --vpc-connector ${{ secrets.GCP_VCP_CONNECTOR }} \
          --set-env-vars REDIS_HOST=${{ secrets.REDIS_AUTH_MICROSERVICE_HOST }},REDIS_PORT=${{ secrets.REDIS_AUTH_MICROSERVICE_PORT }},MYSQL_HOST=${{ secrets.MYSQL_AUTH_MICROSERVICE_HOST }},MYSQL_PORT=${{ secrets.MYSQL_AUTH_MICROSERVICE_PORT }},MYSQL_USER=${{ secrets.MYSQL_AUTH_MICROSERVICE_USERNAME }},MYSQL_PASSWORD=${{ secrets.MYSQL_AUTH_MICROSERVICE_PASSWORD }},MYSQL_DATABASE=${{ secrets.MYSQL_AUTH_MICROSERVICE_DATABASE }}
