name: publish

on: [push]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Build
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/Auth-Microservice:latest

      - name: Deploy
        run: |
          gcloud run deploy helloworld \
          --region europe-north1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/Auth-Microservice \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --vpc-connector connector-redis-cloud-run \
          --set-env-vars REDIS_HOST=REDIS_AUTH_MICROSERVICE_HOST,REDIS_PORT=REDIS_AUTH_MICROSERVICE_PORT,MYSQL_HOST=MYSQL_AUTH_MICROSERVICE_HOST,MYSQL_PORT=MYSQL_AUTH_MICROSERVICE_PORT,MYSQL_USER=MYSQL_AUTH_MICROSERVICE_USERNAME,MYSQL_PASSWORD=MYSQL_AUTH_MICROSERVICE_PASSWORD,MYSQL_DATABASE=MYSQL_AUTH_MICROSERVICE_DATABASE
